# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Settings.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(688, 425)
        Dialog.setSizeGripEnabled(True)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.widget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_general = QtWidgets.QWidget()
        self.tab_general.setObjectName("tab_general")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_general)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame = QtWidgets.QFrame(self.tab_general)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.formLayout_2 = QtWidgets.QFormLayout(self.frame)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.btnColor = QtWidgets.QPushButton(self.frame)
        self.btnColor.setObjectName("btnColor")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.btnColor)
        self.gridLayout_6.addWidget(self.frame, 3, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_general)
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.checkScanCharacter = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkScanCharacter.setObjectName("checkScanCharacter")
        self.gridLayout_2.addWidget(self.checkScanCharacter, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.checkShipNames = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkShipNames.setObjectName("checkShipNames")
        self.gridLayout_2.addWidget(self.checkShipNames, 1, 1, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_general)
        self.groupBox_4.setFlat(True)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.checkNotifyOwn = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkNotifyOwn.setObjectName("checkNotifyOwn")
        self.gridLayout_5.addWidget(self.checkNotifyOwn, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 2, 0, 1, 1)
        self.checkPopupNotification = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkPopupNotification.setObjectName("checkPopupNotification")
        self.gridLayout_5.addWidget(self.checkPopupNotification, 2, 1, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_4, 0, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab_general)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.txtMessageExpiry = QtWidgets.QLineEdit(self.groupBox)
        self.txtMessageExpiry.setObjectName("txtMessageExpiry")
        self.gridLayout_3.addWidget(self.txtMessageExpiry, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.txtKosInterval = QtWidgets.QLineEdit(self.groupBox)
        self.txtKosInterval.setObjectName("txtKosInterval")
        self.gridLayout_3.addWidget(self.txtKosInterval, 1, 1, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_general, "")
        self.tab_map_display = QtWidgets.QWidget()
        self.tab_map_display.setObjectName("tab_map_display")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_map_display)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBoxMap = QtWidgets.QGroupBox(self.tab_map_display)
        self.groupBoxMap.setFlat(True)
        self.groupBoxMap.setObjectName("groupBoxMap")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBoxMap)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.btnMapAddTime = QtWidgets.QPushButton(self.groupBoxMap)
        self.btnMapAddTime.setObjectName("btnMapAddTime")
        self.gridLayout_4.addWidget(self.btnMapAddTime, 2, 0, 1, 1)
        self.cmbAlertType = QtWidgets.QComboBox(self.groupBoxMap)
        self.cmbAlertType.setObjectName("cmbAlertType")
        self.gridLayout_4.addWidget(self.cmbAlertType, 0, 0, 1, 1)
        self.btnMapDelTime = QtWidgets.QPushButton(self.groupBoxMap)
        self.btnMapDelTime.setObjectName("btnMapDelTime")
        self.gridLayout_4.addWidget(self.btnMapDelTime, 2, 1, 1, 1)
        self.tableViewMap = QtWidgets.QTableView(self.groupBoxMap)
        self.tableViewMap.setObjectName("tableViewMap")
        self.gridLayout_4.addWidget(self.tableViewMap, 1, 0, 1, 2)
        self.verticalLayout_3.addWidget(self.groupBoxMap)
        self.tabWidget.addTab(self.tab_map_display, "")
        self.tab_sound = QtWidgets.QWidget()
        self.tab_sound.setObjectName("tab_sound")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_sound)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lstSound = QtWidgets.QTableView(self.tab_sound)
        self.lstSound.setObjectName("lstSound")
        self.gridLayout_7.addWidget(self.lstSound, 0, 0, 1, 5)
        self.label_8 = QtWidgets.QLabel(self.tab_sound)
        self.label_8.setObjectName("label_8")
        self.gridLayout_7.addWidget(self.label_8, 1, 0, 1, 1)
        self.txtSound = QtWidgets.QLineEdit(self.tab_sound)
        self.txtSound.setObjectName("txtSound")
        self.gridLayout_7.addWidget(self.txtSound, 1, 1, 1, 1)
        self.btnSoundSearch = QtWidgets.QPushButton(self.tab_sound)
        self.btnSoundSearch.setObjectName("btnSoundSearch")
        self.gridLayout_7.addWidget(self.btnSoundSearch, 1, 2, 1, 1)
        self.btnPlay = QtWidgets.QPushButton(self.tab_sound)
        self.btnPlay.setObjectName("btnPlay")
        self.gridLayout_7.addWidget(self.btnPlay, 1, 3, 1, 1)
        self.sliderVolume = QtWidgets.QSlider(self.tab_sound)
        self.sliderVolume.setOrientation(QtCore.Qt.Horizontal)
        self.sliderVolume.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.sliderVolume.setObjectName("sliderVolume")
        self.gridLayout_7.addWidget(self.sliderVolume, 1, 4, 1, 1)
        self.tabWidget.addTab(self.tab_sound, "")
        self.tab_regions = QtWidgets.QWidget()
        self.tab_regions.setObjectName("tab_regions")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_regions)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_10 = QtWidgets.QLabel(self.tab_regions)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setTextFormat(QtCore.Qt.PlainText)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.listRegion = QtWidgets.QListWidget(self.tab_regions)
        self.listRegion.setAlternatingRowColors(False)
        self.listRegion.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listRegion.setSelectionRectVisible(True)
        self.listRegion.setObjectName("listRegion")
        self.verticalLayout_2.addWidget(self.listRegion)
        self.label_9 = QtWidgets.QLabel(self.tab_regions)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.txtRegions = QtWidgets.QLineEdit(self.tab_regions)
        self.txtRegions.setObjectName("txtRegions")
        self.verticalLayout_2.addWidget(self.txtRegions)
        self.btnRegionHelp = QtWidgets.QPushButton(self.tab_regions)
        self.btnRegionHelp.setObjectName("btnRegionHelp")
        self.verticalLayout_2.addWidget(self.btnRegionHelp)
        self.tabWidget.addTab(self.tab_regions, "")
        self.tab_chatroom = QtWidgets.QWidget()
        self.tab_chatroom.setObjectName("tab_chatroom")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_chatroom)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_11 = QtWidgets.QLabel(self.tab_chatroom)
        self.label_11.setTextFormat(QtCore.Qt.PlainText)
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_4.addWidget(self.label_11)
        self.txtChatrooms = QtWidgets.QPlainTextEdit(self.tab_chatroom)
        self.txtChatrooms.setObjectName("txtChatrooms")
        self.verticalLayout_4.addWidget(self.txtChatrooms)
        self.tabWidget.addTab(self.tab_chatroom, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.widget)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_4.setText(_translate("Dialog", "Window Background Color :"))
        self.btnColor.setText(_translate("Dialog", "Color..."))
        self.groupBox_2.setTitle(_translate("Dialog", "Chat-Filter"))
        self.label_3.setText(_translate("Dialog", "Scan for Character-Names:"))
        self.checkScanCharacter.setText(_translate("Dialog", "enable"))
        self.label_5.setText(_translate("Dialog", "Scan for Ship-Names"))
        self.checkShipNames.setText(_translate("Dialog", "enable"))
        self.groupBox_4.setTitle(_translate("Dialog", "Other"))
        self.checkNotifyOwn.setText(_translate("Dialog", "enabled"))
        self.label_6.setText(_translate("Dialog", "Notify on own Message:"))
        self.label_7.setText(_translate("Dialog", "Pop-Up notification:"))
        self.checkPopupNotification.setText(_translate("Dialog", "enabled"))
        self.groupBox.setTitle(_translate("Dialog", "in Seconds"))
        self.label.setText(_translate("Dialog", "Message expiry :"))
        self.label_2.setText(_translate("Dialog", "KOS Clipboard interval:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_general), _translate("Dialog", "General"))
        self.groupBoxMap.setTitle(_translate("Dialog", "Alert Settings"))
        self.btnMapAddTime.setText(_translate("Dialog", "add Time"))
        self.btnMapDelTime.setText(_translate("Dialog", "delete Time"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_map_display), _translate("Dialog", "Map-Display"))
        self.label_8.setText(_translate("Dialog", "Sound File:"))
        self.btnSoundSearch.setText(_translate("Dialog", "..."))
        self.btnPlay.setText(_translate("Dialog", "Play"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_sound), _translate("Dialog", "Sound"))
        self.label_10.setText(_translate("Dialog", "Select the regions to keep on the watch list:"))
        self.listRegion.setSortingEnabled(True)
        self.label_9.setText(_translate("Dialog", "Region-Files (comma separated):"))
        self.btnRegionHelp.setText(_translate("Dialog", "Help me on this..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_regions), _translate("Dialog", "Regions"))
        self.label_11.setText(_translate("Dialog", "Enter the chatrooms to watch into the following field. Separate them by comma."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_chatroom), _translate("Dialog", "Chatrooms"))
